version: 0.2

environment_variables:
  plaintext:
    TEMPLATE_FILES: |
      001-vpc.yml
      002-gateway.yml
      003-subnets.yml
      004-routetables.yml
      005-networkacls.yml
#https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#runtime-versions-buildspec-file
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      npm install jsonlint -g
  pre_build:
    commands:
      - echo "Validating CFN templates"
      - |
        for cfn_template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $cfn_template"
        done
    build:
    commands:
      - echo "do nothing"
artifacts:
  files:
    - 001-vpc.yml
    - 002-gateway.yml
    - 003-subnets.yml
    - 004-routetables.yml
    - 005-networkacls.yml
